/**
 * Mishkat Retrieval Types, Options, and Constants — Phase 4
 * 
 * Defines schemas, default configurations, domain affinity maps,
 * and data contracts for hybrid claim-aware retrieval.
 */

import { KNOWLEDGE_DOMAINS, EVIDENCE_TYPES } from '../knowledge/sourceTypes.js';

export const DEFAULT_RETRIEVAL_OPTIONS = Object.freeze({
  topK: 5,
  candidatePoolSize: 20,
  minRelevanceThreshold: 0.012, // RRF threshold to filter zero-result / irrelevant queries
  minSemanticNoiseFloor: 0.60,  // Baseline noise floor for dense embeddings
  rrfK: 60,                     // Reciprocal Rank Fusion constant
  enableMetadataBoost: true,
  metadataBoostWeight: 0.35,
  embeddingProvider: 'auto'     // 'auto' | 'test' | 'gemini'
});

/**
 * Task-to-Domain Affinity Mapping
 * Directs soft boosts toward domains most relevant to the question's task family
 */
export const TASK_DOMAIN_AFFINITY = Object.freeze({
  VERIFY_QURAN: [KNOWLEDGE_DOMAINS.QURAN, KNOWLEDGE_DOMAINS.TAFSIR],
  CORRECT_QUOTE: [KNOWLEDGE_DOMAINS.QURAN, KNOWLEDGE_DOMAINS.HADITH],
  VERIFY_HADITH: [KNOWLEDGE_DOMAINS.HADITH],
  VERIFY_CONSENSUS: [KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH],
  TRANSLATE_CONCEPT: [KNOWLEDGE_DOMAINS.TERMINOLOGY, KNOWLEDGE_DOMAINS.DAWAH],
  HISTORICAL_CLAIM: [KNOWLEDGE_DOMAINS.HISTORY],
  MISCONCEPTION: [KNOWLEDGE_DOMAINS.MISCONCEPTIONS, KNOWLEDGE_DOMAINS.QURAN, KNOWLEDGE_DOMAINS.HADITH, KNOWLEDGE_DOMAINS.HISTORY],
  DEFINE: [KNOWLEDGE_DOMAINS.TERMINOLOGY, KNOWLEDGE_DOMAINS.AQEEDAH, KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.QURAN],
  COMPARE: [KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH, KNOWLEDGE_DOMAINS.TERMINOLOGY],
  WHY: [KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH, KNOWLEDGE_DOMAINS.TAFSIR, KNOWLEDGE_DOMAINS.QURAN],
  PERSONAL_FATWA: [KNOWLEDGE_DOMAINS.FIQH],
  EXPLAIN: [KNOWLEDGE_DOMAINS.TAFSIR, KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH, KNOWLEDGE_DOMAINS.DAWAH],
  VERIFY_CLAIM: [KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH, KNOWLEDGE_DOMAINS.HADITH, KNOWLEDGE_DOMAINS.QURAN],
  GENERAL: [KNOWLEDGE_DOMAINS.DAWAH, KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.HADITH, KNOWLEDGE_DOMAINS.QURAN]
});

/**
 * EvidenceType-to-Domain Affinity Mapping
 */
export const EVIDENCE_DOMAIN_AFFINITY = Object.freeze({
  [EVIDENCE_TYPES.QURANIC_CANONICAL_TEXT]: [KNOWLEDGE_DOMAINS.QURAN],
  [EVIDENCE_TYPES.HADITH_ISNAD_STATUS]: [KNOWLEDGE_DOMAINS.HADITH],
  [EVIDENCE_TYPES.TAFSIR_EXEGESIS]: [KNOWLEDGE_DOMAINS.TAFSIR],
  [EVIDENCE_TYPES.FIQH_OPINIONS]: [KNOWLEDGE_DOMAINS.FIQH],
  [EVIDENCE_TYPES.SCHOLARLY_IJMA_CONFIRMATION]: [KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH],
  [EVIDENCE_TYPES.SCHOLARLY_CONSENSUS_AND_DISAGREEMENT]: [KNOWLEDGE_DOMAINS.FIQH, KNOWLEDGE_DOMAINS.AQEEDAH],
  [EVIDENCE_TYPES.HISTORICAL_DOCUMENTATION]: [KNOWLEDGE_DOMAINS.HISTORY],
  [EVIDENCE_TYPES.THEOLOGICAL_PROPOSITION]: [KNOWLEDGE_DOMAINS.AQEEDAH],
  [EVIDENCE_TYPES.LEXICAL_DEFINITION]: [KNOWLEDGE_DOMAINS.TERMINOLOGY],
  [EVIDENCE_TYPES.MISCONCEPTION_REBUTTAL]: [KNOWLEDGE_DOMAINS.MISCONCEPTIONS],
  [EVIDENCE_TYPES.DAWAH_CLARIFICATION]: [KNOWLEDGE_DOMAINS.DAWAH],
  [EVIDENCE_TYPES.TEXTUAL_EVIDENCE]: [KNOWLEDGE_DOMAINS.QURAN, KNOWLEDGE_DOMAINS.HADITH, KNOWLEDGE_DOMAINS.FIQH]
});
